language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.2"
